#!/bin/bash

set -e

PROG=$(basename $0)

usage() {
  echo "$PROG <commit message>"
  exit 1
}

[[ -n $1 ]] || usage

git stash
git pull origin blog/hexo --rebase
git stash pop || echo "no stash to pop"
git add .
git commit -m "$1"

hexo g
hexo d

